spring:
  application:
    name: bookstore-backend-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookstoremicro
    username: root
    password: sasa
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
server:
  port: 0