server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: bookStore-backend
          uri: lb://BOOKSTORE-BACKEND-SERVICE
          predicates:
            - Path=/api/**
        - id: bookStore-UI
          uri: lb://BOOKSTORE-UI-SERVICE
          predicates:
            - Path=/bookstore/**
        - id: bookStore-payment
          uri: lb://BOOKSTORE-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: bookStore-transport
          uri: lb://BOOKSTORE-TRANSPORT-SERVICE
          predicates:
            - Path=/transport/**
